PLACES = [
    {
        "name": "Pleasanton Regional Park",
        "maps_query": "Pleasanton Ridge Regional Park",
        "drive_minutes": {"San Jose": 35, "San Francisco": 60},
        "zone": "1",
        "trip_type": "day trip",
        "vibes": ["hiking", "hills", "views"],
        "modes": ["day"],
        "difficulty": "easy",
        "best_time": "morning or late afternoon",
        "night_friendly": False,
        "stargazing": False,
        "photo_zones": ["hilltops", "valley views"],
        "wildlife": ["deer", "hawks"],
        "weather_note": "Warm and dry inland. Hot in summer.",
        "description": "Green hills and panoramic valley views."
    },
    {
        "name": "Del Valle Regional Park",
        "maps_query": "Del Valle Regional Park Livermore",
        "drive_minutes": {"San Jose": 50, "San Francisco": 75},
        "zone": "1",
        "trip_type": "day trip",
        "vibes": ["water", "hiking", "views"],
        "modes": ["day"],
        "difficulty": "easy",
        "best_time": "morning",
        "night_friendly": False,
        "stargazing": False,
        "photo_zones": ["lake shore", "hills"],
        "wildlife": ["birds", "fish"],
        "weather_note": "Warm inland. Great for swimming in summer.",
        "description": "SUP boards, picnic by the water, calm vibes."
    },
    {
        "name": "Half Moon Bay",
        "maps_query": "Half Moon Bay State Beach",
        "drive_minutes": {"San Jose": 55, "San Francisco": 45},
        "zone": "1",
        "trip_type": "day trip",
        "vibes": ["ocean", "sunset", "photography"],
        "modes": ["day", "sunset", "night"],
        "difficulty": "easy",
        "best_time": "golden hour",
        "night_friendly": True,
        "stargazing": False,
        "photo_zones": ["cliffs", "beach", "pumpkin fields in fall"],
        "wildlife": ["shore birds", "seals"],
        "weather_note": "Cool and foggy in summer. Warmer in fall.",
        "description": "Cliff walks, fresh seafood, dramatic sunsets."
    },
    {
        "name": "Santa Cruz",
        "maps_query": "Santa Cruz Beach Boardwalk",
        "drive_minutes": {"San Jose": 50, "San Francisco": 90},
        "zone": "1",
        "trip_type": "day trip",
        "vibes": ["ocean", "surf", "chill"],
        "modes": ["day", "sunset", "night"],
        "difficulty": "easy",
        "best_time": "morning or afternoon",
        "night_friendly": True,
        "stargazing": False,
        "photo_zones": ["beach", "boardwalk", "cliffs"],
        "wildlife": ["pelicans", "sea otters"],
        "weather_note": "Mild year round. Foggy mornings.",
        "description": "Beaches, surf vibes, relaxed coastal town."
    },
    {
        "name": "Big Basin Redwoods",
        "maps_query": "Big Basin Redwoods State Park",
        "drive_minutes": {"San Jose": 70, "San Francisco": 90},
        "zone": "1",
        "trip_type": "day trip",
        "vibes": ["forest", "hiking", "photography"],
        "modes": ["day"],
        "difficulty": "medium",
        "best_time": "morning",
        "night_friendly": False,
        "stargazing": False,
        "photo_zones": ["giant sequoias", "creek trails"],
        "wildlife": ["banana slugs", "woodpeckers", "deer"],
        "weather_note": "Cool and shaded year round.",
        "description": "Giant sequoias and shady forest trails."
    },
    {
        "name": "Point Lobos",
        "maps_query": "Point Lobos State Natural Reserve",
        "drive_minutes": {"San Jose": 80, "San Francisco": 130},
        "zone": "1",
        "trip_type": "day trip",
        "vibes": ["ocean", "photography", "wildlife", "sunset"],
        "modes": ["day", "sunset"],
        "difficulty": "easy",
        "best_time": "morning or golden hour",
        "night_friendly": False,
        "stargazing": False,
        "photo_zones": ["cliffs", "cypress trees", "tide pools"],
        "wildlife": ["sea lions", "seals", "sea birds"],
        "weather_note": "Cool, windy, coastal.",
        "description": "Ocean cliffs, wildlife, dramatic coastal photography."
    },
    {
        "name": "Mount Tamalpais",
        "maps_query": "Mount Tamalpais State Park",
        "drive_minutes": {"San Jose": 75, "San Francisco": 45},
        "zone": "1",
        "trip_type": "day trip",
        "vibes": ["hiking", "views", "sunset", "photography"],
        "modes": ["day", "sunset", "night", "stargazing"],
        "difficulty": "medium",
        "best_time": "early morning or sunset",
        "night_friendly": True,
        "stargazing": True,
        "photo_zones": ["summit views", "bay panorama", "fog layers"],
        "wildlife": ["hawks", "deer", "foxes"],
        "weather_note": "Cool and windy at summit. Fog common.",
        "sky_note": "Good dark skies away from summit parking.",
        "description": "Bay panorama from above the clouds, hiking above fog."
    },
    {
        "name": "Pinnacles National Park",
        "maps_query": "Pinnacles National Park",
        "drive_minutes": {"San Jose": 90, "San Francisco": 135},
        "zone": "1",
        "trip_type": "day trip",
        "vibes": ["hiking", "caves", "wildlife", "photography"],
        "modes": ["day", "stargazing"],
        "difficulty": "medium",
        "best_time": "early morning",
        "night_friendly": False,
        "stargazing": True,
        "photo_zones": ["rock formations", "cave entrances", "condor spotting"],
        "wildlife": ["California condors", "bats", "deer"],
        "weather_note": "Very hot in summer. Best in spring or fall.",
        "sky_note": "Dark sky area. Great for stargazing.",
        "description": "Unique rock formations, caves, and condor spotting."
    },
    {
        "name": "Point Reyes Lighthouse",
        "maps_query": "Point Reyes Lighthouse",
        "drive_minutes": {"San Jose": 120, "San Francisco": 90},
        "zone": "1",
        "trip_type": "day trip",
        "vibes": ["ocean", "wildlife", "photography", "sunset"],
        "modes": ["day", "sunset"],
        "difficulty": "easy",
        "best_time": "morning or golden hour",
        "night_friendly": False,
        "stargazing": False,
        "photo_zones": ["lighthouse", "wild beaches", "elk fields"],
        "wildlife": ["elk", "whales", "seals", "deer"],
        "weather_note": "Windy and cool year round. Fog common.",
        "description": "Wild beaches, historic lighthouse, elk and whale watching."
    },
    {
        "name": "Big Sur",
        "maps_query": "Big Sur California",
        "drive_minutes": {"San Jose": 150, "San Francisco": 210},
        "zone": "2",
        "trip_type": "weekend",
        "vibes": ["ocean", "photography", "sunset", "hiking"],
        "modes": ["day", "sunset", "night", "stargazing"],
        "difficulty": "medium",
        "best_time": "golden hour",
        "night_friendly": True,
        "stargazing": True,
        "photo_zones": ["Bixby Bridge", "McWay Falls", "Highway 1 cliffs"],
        "wildlife": ["condors", "sea otters", "deer"],
        "weather_note": "Mild year round. Fog in summer mornings.",
        "sky_note": "Excellent dark skies. One of the best spots near Bay Area.",
        "description": "Legendary Highway 1, Bixby Bridge, McWay Falls waterfall."
    },
]
